arb-dir: lib/core/l10n































































template-arb-file: app_en.arb































































output-localization-file: s.dart































































output-class: S































































nullable-getter: false































































use-escaping: true































































untranslated-messages-file: missing_translations.txt































































preferred-locale: fr

