name: depenses_app
description: Application de gestion des dépenses pour Ambulance Saint-Jean Québec
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  provider: ^6.1.2
  http: ^1.2.2
  shared_preferences: ^2.2.2
  url_launcher: ^6.3.0
  path_provider: ^2.1.4
  image_picker: ^1.1.2
  file_picker: ^8.1.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  generate: true  # nécessaire pour gen-l10n

  assets:
    - assets/images/logo.png
    - assets/splash/

  # --- Configuration de l’icône d’application ---
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/logo.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/images/logo.png
  remove_alpha_ios: true

# --- Configuration de l’écran de démarrage ---
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash/splash.png
  color_dark: "#000000"
  image_dark: assets/splash/splash_dark.png
  android: true
  ios: true
  web: true
  android_12:
    color: "#FFFFFF"
    image: assets/splash/splash.png
    color_dark: "#000000"
    image_dark: assets/splash/splash_dark.png
